stages:
    - style
    - test_code
    - test_docs
    - publish_docs

tests:
    tags:
        - python
    script:
        - pyenv versions
        - pyenv local 2.7 3.4.6 3.5.3 3.6.2
        - tox -r -vv -i https://cosmo-pypi.phys.ethz.ch/simple
    stage: test_code
    artifacts:
           paths:
             - htmlcov/

style:
    tags:
        - python
    script:
        - pyenv local 2.7 3.4.6 3.5.3 3.6.2
        - tox -e style -i https://cosmo-pypi.phys.ethz.ch/simple
    allow_failure: true
    stage: style


docs:
    tags:
        - python
    script:
        - pyenv local 2.7 3.4.6 3.5.3 3.6.2
        - tox -e docs -i https://cosmo-pypi.phys.ethz.ch/simple
    stage: test_docs
    dependencies:
          - tests

publish_docs:
    tags:
        - python
    script:
        - pyenv local 2.7 3.4.6 3.5.3 3.6.2
        - tox -e publish_docs -i https://cosmo-pypi.phys.ethz.ch/simple
    when: manual
    only:
        - master
    stage: publish_docs
